name: INT

on: [push]

jobs:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: oshxona.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
